server/dmhunter/urls.py
from django.urls import path

from . import views

app_name = 'dmhunter'

urlpatterns = [
    path('', views.index, name='index'),
    path('mpinstall', views.mpinstall, name='mpinstall'),
    path('qquninstall', views.qquninstall, name='qquninstall'),
    path('webclient', views.webclient, name='webclient'),
    path('mpcallback/<int:id>', views.mpcallback, name='mpcallback'),
    path('cqhttpcallback', views.cqhttpcallback, name='cqhttpcallback'),
]

server/server/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, reverse


urlpatterns = [
    path('', lambda request: redirect(reverse('dmhunter:index')), name='index'),
    path('dmhunter/', include('dmhunter.urls')),
    path('admin/', admin.site.urls),
]

server/dmhunter/models.py
import re

from django.db import models

# Create your models here.

class Connector(models.Model):
    token = models.CharField(max_length=64, unique=True, default=None)
    aeskey = models.CharField(max_length=64, unique=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Gh(models.Model):
    appid = models.CharField(max_length=64, unique=True, default=None)
    user_name = models.CharField(max_length=64, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Openid(models.Model):
    openid = models.CharField(max_length=64, unique=True, default=None)
    gh = models.ForeignKey(Gh, on_delete=models.PROTECT)
    user_filled_id = models.CharField(max_length=64, blank=True, default='')
    joined_group = models.ForeignKey('Group', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Subscription(models.Model):
    token = models.CharField(max_length=64, unique=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Group(models.Model):
    gh = models.ForeignKey(Gh, on_delete=models.PROTECT)
    name = models.CharField(max_length=64, default=None)
    regular_name = models.CharField(max_length=64, unique=True, default=None)
    owner = models.ForeignKey(Openid, on_delete=models.PROTECT)
    subscription = models.OneToOneField(Subscription, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    pattern_regular_name = re.compile('^[0-9A-Za-z \-_\.]+$')
    @classmethod
    def regularize(cls, name):
        m = cls.pattern_regular_name.match(name)
        if not m or name != name.strip() or '  ' in name:
           return None
        return name.lower()

    class Meta:
        unique_together = ('gh', 'regular_name', )


class Message(models.Model):
    openid = models.ForeignKey(Openid, on_delete=models.PROTECT)
    gh = models.ForeignKey(Gh, on_delete=models.PROTECT)
    group = models.ForeignKey(Group, null=True, blank=True, on_delete=models.PROTECT)
    from_appid = models.CharField(max_length=64, db_index=True, default=None)
    to_user_name = models.CharField(max_length=64, db_index=True, default=None)
    from_user_name = models.CharField(max_length=64, db_index=True, default=None)
    create_time = models.BigIntegerField()
    msg_type = models.CharField(max_length=64, db_index=True, default=None)
    content = models.TextField()
    msg_id = models.BigIntegerField()
    xml_content = models.TextField()
    reply = models.TextField(null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

server/dmhunter/views.py
import base64
import channels.layers
import hashlib
import hmac
import json
import random
import re
import socket
import string
import struct
import time
import xml.etree.ElementTree as ET

from asgiref.sync import async_to_sync
from django.conf import settings
from django.core.exceptions import PermissionDenied, ValidationError
from django.db import transaction
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from Crypto.Cipher import AES
from . import consumers
from .helpers import *
from .models import *

# Create your views here.

def index(request):
    return render(request, 'dmhunter/index.html')

def mpinstall(request):
    if request.method == 'POST':
        if settings.USE_X_FORWARDED_HOST:
            host = request.META['HTTP_X_FORWARDED_HOST']
        else:
            host = request.META['HTTP_HOST']
        token = gen_token(32)
        aeskey = gen_token(43)
        with transaction.atomic():
            connector = Connector.objects.create(token=token, aeskey=aeskey)
            url = 'https://{:s}{:s}'.format(host, reverse('dmhunter:mpcallback', kwargs={'id': connector.id}))
            return render(request, 'dmhunter/mpinstall.html', {'id': connector.id, 'url': url, 'token': token, 'aeskey': aeskey})
    return render(request, 'dmhunter/mpinstall.html')

def qquninstall(request):
    if request.method == 'POST':
        verification_code = gen_token(16)
        client_token = gen_token(32)
        qqun_app = QqunApp.objects.create(group_id=None, verification_code=verification_code, client_token=client_token)
        return render(request, 'dmhunter/qquninstall.html', {'qq_dmrobot': settings.QQ_DMROBOT, 'id': qqun_app.id, 'verification_code': verification_code, 'client_token': client_token})
    return render(request, 'dmhunter/qquninstall.html', {'qq_dmrobot': settings.QQ_DMROBOT})

def webclient(request):
    return render(request, 'dmhunter/webclient.html')

@csrf_exempt
def mpcallback(request, id):
    connector = get_object_or_404(Connector.objects, id=id)
    token = connector.token
    aeskey = connector.aeskey

    signature = request.GET.get('signature', '')
    timestamp = request.GET.get('timestamp', '')
    nonce = request.GET.get('nonce', '')
    tmp_arr = sorted([token, timestamp, nonce])
    tmp_str = ''.join(tmp_arr)
    tmp_str = hashlib.sha1(tmp_str.encode()).hexdigest()
    if tmp_str != signature:
        raise PermissionDenied

    if request.method == 'GET':
        return HttpResponse(request.GET.get('echostr', ''))

    et1 = ET.fromstring(request.body.decode())
    encrypt = et1.find('Encrypt').text
    key = base64.b64decode(aeskey + '=')
    cryptor = AES.new(key, AES.MODE_CBC, key[:16])
    plain_text = cryptor.decrypt(base64.b64decode(encrypt))
    content = plain_text[16:-plain_text[-1]]
    xml_len = socket.ntohl(struct.unpack('I',content[:4])[0])
    xml_content = content[4:xml_len + 4].decode()
    et2 = ET.fromstring(xml_content)

    from_appid = content[xml_len + 4:].decode()
    openid = request.GET['openid']
    to_user_name = et1.find('ToUserName').text
    from_user_name = et2.find('FromUserName').text
    create_time = int(et2.find('CreateTime').text)
    msg_type = et2.find('MsgType').text
    content = et2.find('Content')
    if content is not None:
        content = content.text
    else:
        content = ''
    msg_id = et2.find('MsgId')
    if msg_id is not None:
        msg_id = int(msg_id.text)
    else:
        msg_id = 0
    assert openid == from_user_name

    with transaction.atomic():
        gh_obj, _ = Gh.objects.get_or_create(appid=from_appid, defaults={'user_name': to_user_name})
        openid_obj, _ = Openid.objects.get_or_create(openid=openid, defaults={'gh': gh_obj})
        message_obj = Message.objects.create(openid=openid_obj, gh=gh_obj, from_appid=from_appid, to_user_name=to_user_name, from_user_name=from_user_name, create_time=create_time, msg_type=msg_type, content=content, msg_id=msg_id, xml_content=xml_content)
    assert openid_obj.gh == gh_obj

    reply = None

    if content.lstrip().startswith('@'):
        m1 = re.match('@register\s*=', content)
        m2 = re.match('\s*@(class|id)\s*[=＝]', content.lower())
        m3 = re.match('@gettoken\s*=', content)
        if m1:
            name = content[len(m1.group(0)):].strip()
            regular_name = Group.regularize(name)
            if regular_name:
                if Group.objects.filter(gh=gh_obj, regular_name=regular_name).exists():
                    reply = '注册失败：名称被占用'
                else:
                    with transaction.atomic():
                        subscription = Subscription.objects.create(token=gen_token(16))
                        Group.objects.create(gh=gh_obj, name=name, regular_name=regular_name, owner=openid_obj, subscription=subscription)
                    reply = f'成功注册新频道 {name}'
            else:
                reply = '注册失败：名称应使用字母、数字、空格、减号、下划线、小数点'
        elif m2:
            action = m2.group(1).lower()
            name = content[len(m2.group(0)):].strip()
            if action == 'class':
                if not name:
                    openid_obj.joined_group = None
                    openid_obj.save()
                    reply = '已退出频道'
                else:
                    regular_name = Group.regularize(name)
                    if regular_name:
                        group = Group.objects.filter(gh=gh_obj, regular_name=regular_name).first()
                        if group:
                            openid_obj.joined_group = group
                            openid_obj.save()
                            reply = f'成功加入频道 {group.name}'
                            if name != group.name:
                                reply += '（不区分大小写）'
                        else:
                            reply = '加入失败：频道不存在'
                    else:
                        reply = '加入失败：频道名称格式错误'
            else:  # action == 'id'
                is_charset_valid = all(c in string.digits + string.ascii_letters for c in name)
                if not is_charset_valid:
                    reply = 'ID 格式错误，只允许字母数字'
                elif len(name) > 18:
                    reply = 'ID 过长'
                else:
                    if name:
                        reply = '更新 ID 成功'
                    else:
                        reply = '删除 ID 成功'
                    openid_obj.user_filled_id = name
                    openid_obj.full_clean()
                    openid_obj.save()
        elif m3:
            name = content[len(m3.group(0)):].strip()
            regular_name = Group.regularize(name)
            if regular_name:
                group = Group.objects.filter(gh=gh_obj, regular_name=regular_name).first()
                if group.owner == openid_obj:
                    reply = f'{group.subscription.id}:{group.subscription.token}'
                else:
                    reply = '获取 token 失败：权限错误'
            else:
                reply = '获取 token 失败：频道名称错误'
        elif content.strip() == '@class':
            group = openid_obj.joined_group
            if openid_obj.joined_group:
                reply = f'当前弹幕频道为 {openid_obj.joined_group.name}'
            else:
                reply = '未加入弹幕频道'
        else:
            reply = '指令错误'
    elif content:
        if openid_obj.joined_group:
            group_name = 'dmhunter_chat_{:d}'.format(openid_obj.joined_group.subscription.id)
            if consumers.group_channel_names[group_name]:
                message_obj.group = openid_obj.joined_group  # delayed save. save with reply at the same time
                channel_layer = channels.layers.get_channel_layer()
                async_to_sync(channel_layer.group_send)(
                    group_name,
                    {
                        'type': 'broadcast',
                        'message': {
                            'type': 'chat.mp_msg',
                            'mp_msg': {
                                'group_name': openid_obj.joined_group.name,
                                'openid': openid,
                                'user_filled_id': openid_obj.user_filled_id,
                                'msg_type': msg_type,
                                'content': content,
                            },
                        },
                    }
                )
                reply = '弹幕发射~升空！'
            else:
                reply = '当前频道未接收弹幕'
        else:
            reply = '未加入弹幕频道'

    if reply:
        message_obj.reply=reply
        message_obj.save()

    if reply:
        xml = ET.Element('xml')
        timestamp = int(time.time())
        child = ET.SubElement(xml, 'ToUserName')
        child.text = openid
        child = ET.SubElement(xml, 'FromUserName')
        child.text = to_user_name
        child = ET.SubElement(xml, 'CreateTime')
        child.text = str(timestamp)
        child = ET.SubElement(xml, 'MsgType')
        child.text = 'text'
        child = ET.SubElement(xml, 'Content')
        child.text = reply
        text = ET.tostring(xml, encoding='utf-8')

        text = gen_token(16).encode() + struct.pack('I', socket.htonl(len(text))) + text + from_appid.encode()
        text_length = len(text)
        block_size = 32
        amount_to_pad = block_size - (text_length % block_size)
        if amount_to_pad == 0:
            amount_to_pad = block_size
        text += bytes([amount_to_pad] * amount_to_pad)
        cryptor = AES.new(key, AES.MODE_CBC, key[:16])
        text = base64.b64encode(cryptor.encrypt(text)).decode()
        tmp_arr = sorted([token, str(timestamp), nonce, text])
        tmp_str = ''.join(tmp_arr)
        signature = hashlib.sha1(tmp_str.encode()).hexdigest()

        xml = ET.Element('xml')
        child = ET.SubElement(xml, 'Encrypt')
        child.text = text

server/dmhunter/templates/dmhunter/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}DM Hunter{% endblock %}</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		{% block head %}{% endblock %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
		<style>
body {
	background-color:#efefef;
}
		</style>
	</head>
	<body>
		{% include "./nav.html" %}
		{% block container %}
		<div class="container mt-4 mb-5">
			{% if messages %}
				{% for message in messages %}
					{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
						<div class="alert alert-danger" role="alert">{{ message }}</div>
					{% else %}
						<div class="alert alert-info" role="alert">{{ message }}</div>
					{% endif %}
				{% endfor %}
			{% endif %}
			{% block content %}{{ content }}{% endblock %}
		</div>
		{% endblock %}
		{% include "./footer.html" %}
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9+4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		{% block postscript %}{% endblock %}
	</body>
</html>

server/dmhunter/templates/dmhunter/footer.html
{% load static %}
<footer class="text-muted" style="background-color: #f0f0f0;">
	<div class="container p-3 p-md-4 text-center">
		<p class="mb-0">
			<a href="http://www.beian.miit.gov.cn/">京ICP备18048112号-1</a><br>
		</p>
		<p>
			DM Hunter 0.2.0-alpha
			|
			UI powered by <a href="https://getbootstrap.com/">Bootstrap</a>
		</p>
	</div>
</footer>

server/dmhunter/templates/dmhunter/index.html
{% extends "./base.html" %}

{% block content %}
<h1>DM Hunter</h1>
<div class="mt-3">
	<p>
		<a class="btn btn-primary" href="{% url 'dmhunter:mpinstall' %}">微信接入</a>
		<a class="btn btn-primary" href="{% url 'dmhunter:webclient' %}">测试</a>
	</p>
</div>
<div style="height: 400px;"></div>
{% endblock %}

server/dmhunter/templates/dmhunter/mpinstall.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1>微信接入</h1>

<p>请按以下指引接入 DM Hunter。</p>
<ol>
	<li><p>在微信公众平台 <a href="https://mp.weixin.qq.com/" target="_blank" rel="noreferrer">https://mp.weixin.qq.com/</a> 申请订阅号。主体为个人或法人均可，无需认证。</p></li>
	<li><p>左侧菜单栏转到“开发 -> 基本配置”，修改服务器配置。</p></li>
	<ul>
		<li><label style="width: 12em;">服务器地址(URL)</label>{% if url %}<code>{{ url }}</code>{% else %}<img src="{% static 'dmhunter/img/wait16.gif' %}"> 等待获取{% endif %}</li>
		<li><label style="width: 12em;">令牌(Token)</label>{% if token %}<code>{{ token }}</code>{% else %}<img src="{% static 'dmhunter/img/wait16.gif' %}"> 等待获取{% endif %}<span class="text-danger ml-4">严禁泄露</span></li>
		<li><label style="width: 12em;">消息加解密密钥</label>{% if aeskey %}<code>{{ aeskey }}</code>{% else %}<img src="{% static 'dmhunter/img/wait16.gif' %}"> 等待获取{% endif %}<span class="text-danger ml-4">严禁泄露</span></li>
		<li><label style="width: 12em;">消息加解密方式</label>安全模式</li>
	</ul>
	<p>只要能成功保存就说明以上信息填写正确。</p>
	<li>
		<p>点击“启用”。启用后，订阅号原本的自动回复会失效。</p>
	</li>
</ol>

<form method="POST">
	{% csrf_token %}
	<p><input type="submit" {% if client_token %}class="btn btn-primary" value="获取 Tokens" disabled{% else %}class="btn btn-primary" value="获取 Tokens"{% endif %}></p>
</forM>
<p>注意事项</p>
<ol>
	<li>以上所有 Token、URL、密钥只会显示一次。如果遗忘了任何一项，只能重新接入（重做第 2 ~ 3 步）。</li>
	<li>严禁泄露微信公众平台服务器配置的 Token 和密钥。</li>
</ol>

<pre>
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
</pre>

{% endblock %}

server/dmhunter/templates/dmhunter/nav.html
<header class="navbar navbar-expand navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'dmhunter:index' %}">DM Hunter</a>
	<div class="navbar-nav-scroll">
		<ul class="navbar-nav">
			<li class="nav-item"><a class="nav-link" href="{% url 'dmhunter:index' %}">首页</a></li>
			<li class="nav-item"><a class="nav-link" href="{% url 'dmhunter:mpinstall' %}">微信接入</a></li>
			<li class="nav-item"><a class="nav-link" href="{% url 'dmhunter:webclient' %}">测试</a></li>
		</ul>
	</div>
</header>

server/dmhunter/templates/dmhunter/qquninstall.html
{% extends "./base.html" %}
{% load static %}

{% block content %}
<h1>QQ 接入</h1>

<p>请按以下指引接入 DM Hunter。</p>
<ol>
	<li><p>添加 QQ 号 {{ qq_dmrobot }}（昵称 DM-robot）为好友，将其加进 QQ 群。</p></li>
	<li><p>在群内发送验证码，DM-robot 自动回复“弹幕绑定成功”。</p></li>
	<ul>
		<li><label style="width: 12em;">验证码</label>{% if verification_code %}<code>{{ verification_code }}</code>{% else %}<img src="{% static 'dmhunter/img/wait16.gif' %}"> 等待获取{% endif %}</li>
	</ul>
	<li><p>将以下 Token 填在弹幕客户端中。</p></li>
	<ul>
		<li><label style="width: 12em;">弹幕客户端 Token</label>{% if id and client_token %}<code>{{id}}:{{ client_token }}</code>{% else %}<img src="{% static 'dmhunter/img/wait16.gif' %}"> 等待获取{% endif %}<span class="text-danger ml-4">持有该 Token 的任何人会获得该 QQ 群的所有消息以便弹幕显示</span></li>
	</ul>
</ol>

<form method="POST">
	{% csrf_token %}
	<p><input type="submit" {% if client_token %}class="btn btn-primary" value="获取 Tokens" disabled{% else %}class="btn btn-primary" value="获取 Tokens"{% endif %}></p>
</forM>
<p>注意事项</p>
<ol>
	<li>以上所有验证码、Token 只会显示一次。如果遗忘了任何一项，只能重新接入。</li>
	<li>如果同一个群重复接入，则只有最后一次接入的生效。</li>
	<li>持有弹幕客户端 Token 的任何人会获得该 QQ 群的所有消息以便弹幕显示。</li>
</ol>

<pre>
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
</pre>

{% endblock %}

server/dmhunter/templates/dmhunter/webclient.html
{% extends "./base.html" %}
{% load static %}

{% block head %}
<style>
#basic-addon1, #basic-addon1:hover{
	color: #333;
}

pre#chat-log {
	padding: 9.5px;
	font-size: 13px;
	word-break: break-all;
	word-wrap: break-word;
	color: #333;
	background-color: #f5f5f5;
	border: 1px solid #ccc;
	border-radius: 4px;
}
</style>
{% endblock %}

{% block content %}
<h1>弹幕频道测试<span class="ml-3 text-secondary" style="font-size: 40%;">网页版</span></h1>

<p class="mt-3">请输入客户端 Token</p>
<form>
	<div class="form-group row">
		<div class="input-group col-sm-6" id="div-client-token">
			<input type="text" class="form-control" id="input-client-token" placeholder="000:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" aria-label="client_token" aria-describedby="basic-addon1">
			<div class="input-group-append">
				<a class="input-group-text" id="basic-addon1" href=""><i class="fa fa-eye" aria-hidden="true"></i></a>
			</div>
		</div>
	</div>
	<div class="form-group row">
		<div class="input-group col-sm-6">
			<button type="submit" class="btn btn-primary" id="connect-btn">连接</button>
		</div>
	</div>
</form>

<pre id="chat-log">
==== logging ====
</pre>

<pre>
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
</pre>
{% endblock %}

{% block postscript %}
<script>
'use strict';

$(document).ready(function () {
	var btn = document.querySelector('#connect-btn');
	var pre = document.querySelector('#chat-log');
	var input = document.querySelector('#input-client-token');

	function connect(mp_app_id, client_token) {
		if (!mp_app_id || !client_token) {
			pre.textContent += 'Bad token\n';
			return;
		}
		btn.setAttribute('disabled', '');

		var chatSocket = new WebSocket(location.protocol.replace('http', 'ws') + '//' + location.host + '/dmhunter/ws/chat/');

		chatSocket.onopen = function (e) {
			pre.textContent += 'WebSocket OPEN\n';
			chatSocket.send(JSON.stringify({
				'type': 'client.version',
				'version': '0.2.1',
			}));
			chatSocket.send(JSON.stringify({
				'type': 'client.subscribe',
				'apps': [{'app_id': mp_app_id, 'client_token': client_token}],
			}));
		};

		chatSocket.onmessage = function (e) {
			var event = JSON.parse(e.data);
			if (event.type == 'server.alert') {
				pre.textContent += ('server.alert: ' + event.alert + '\n');
			} else if (event.type == 'chat.mp_msg') {
				var mp_msg = event.mp_msg;
				var username = mp_msg.openid;
				if (mp_msg.user_filled_id)
					username += '(' + mp_msg.user_filled_id + ')';
				pre.textContent += (username + ': ' + mp_msg.content + '\n');
			} else if (event.type == 'chat.qqun_msg') {
				var qqun_msg = event.qqun_msg;
				pre.textContent += ((qqun_msg.card || qqun_msg.nickname) + '(' + qqun_msg.user_id + '): ' + qqun_msg.message + '\n');
			}
		};

		chatSocket.onclose = function (e) {
			pre.textContent += 'WebSocket CLOSED\n';
			btn.removeAttribute('disabled');
		};
	}

	$(btn).on('click', function (event) {
        event.preventDefault();
		var arr = input.value.trim().split(':');
		var mp_app_id = parseInt(arr[0]);
		var client_token = arr[1];
		connect(mp_app_id, client_token);
	});

    $('#div-client-token a').on('click', function (event) {
        event.preventDefault();
        if ($('#div-client-token input').attr('type') == 'text') {
            $('#div-client-token input').attr('type', 'password');
            $('#div-client-token i').addClass('fa-eye-slash');
            $('#div-client-token i').removeClass('fa-eye');
        } else if ($('#div-client-token input').attr('type') == 'password'){
            $('#div-client-token input').attr('type', 'text');
            $('#div-client-token i').removeClass('fa-eye-slash');
            $('#div-client-token i').addClass('fa-eye');
        }
    });
});
</script>
{% endblock %}